openExample('spc_channel/UrbanChannelLinkAnalysisAndVisualizationUsingRayTracingExample')


% Freedom Mobile
% freedom_tx = txsite(Name="Freedom Mobile Tx", ...
%     Latitude=45.380833, ...
%     Longitude=-75.699167, ...
%     AntennaHeight=30, ...
%     TransmitterPower=3007.1, ...
%     Antenna='isotropic',...
%     TransmitterFrequency=2.1e9);
% 
% Telus
% telus_tx1 = txsite(Name="Telus Tx 1", ...
%     Latitude=45.385125, ...
%     Longitude=-75.697086, ...
%     AntennaHeight=28, ...
%     TransmitterPower=199.5, ...
%     Antenna='isotropic',...
%     TransmitterFrequency=2.6e9);