% https://www.mathworks.com/help/comm/ug/urban-channel-link-analysis-and-visualization-using-ray-tracing.html
clc;


viewer = siteviewer(Buildings="carleton.osm",Basemap="topographic");

tx = txsite(Name="Small cell transmitter", ...
    Latitude=45.38647, ...
    Longitude=-75.6976, ...
    AntennaHeight=10, ...
    TransmitterPower=5, ...
    TransmitterFrequency=28e9);
show(tx)