% https://www.mathworks.com/help/comm/ug/urban-channel-link-analysis-and-visualization-using-ray-tracing.html
clc;

max_range = 100;

% viewer = siteviewer(Buildings="carleton.osm",Basemap="topographic");
viewer = siteviewer(Buildings="carleton_with_surroundings.osm",Basemap="topographic");



% Rogers
rogers_tx1 = txsite(Name="Rogers Tx 1", ...
    Latitude=45.38647, ...
    Longitude=-75.6976, ...
    AntennaHeight=39, ...
    TransmitterPower=28.2, ...
    Antenna='isotropic',...
    TransmitterFrequency=3.5e9);

rogers_tx2 = txsite(Name="Rogers Tx 2", ...
    Latitude=45.38269, ...
    Longitude=-75.6993, ...
    AntennaHeight=85, ...
    TransmitterPower=28.2, ...
    Antenna='isotropic',...
    TransmitterFrequency=3.5e9);

rogers_tx3 = txsite(Name="Rogers Tx 3", ...
    Latitude=45.37504, ...
    Longitude=-75.6927, ...
    AntennaHeight=30, ...
    TransmitterPower=28.2, ...
    Antenna='isotropic',...
    TransmitterFrequency=3.5e9);

% Freedom Mobile
% freedom_tx = txsite(Name="Freedom Mobile Tx", ...
%     Latitude=45.380833, ...
%     Longitude=-75.699167, ...
%     AntennaHeight=30, ...
%     TransmitterPower=3007.1, ...
%     Antenna='isotropic',...
%     TransmitterFrequency=2.1e9);
% 
% Telus
% telus_tx1 = txsite(Name="Telus Tx 1", ...
%     Latitude=45.385125, ...
%     Longitude=-75.697086, ...
%     AntennaHeight=28, ...
%     TransmitterPower=199.5, ...
%     Antenna='isotropic',...
%     TransmitterFrequency=2.6e9);

show(tx1);
show(tx2);
show(tx3);


% Testing
rtpm = propagationModel("raytracing", ...
    Method="sbr", ...
    MaxNumReflections=0, ...
    BuildingsMaterial="concrete", ...
    TerrainMaterial="concrete");
coverage(rogers_tx1,rtpm, ...
    SignalStrengths=-120:-5, ...
    MaxRange=max_range, ...
    Resolution=3, ...
    Transparency=0.6)
coverage(rogers_tx2,rtpm, ...
    SignalStrengths=-120:-5, ...
    MaxRange=max_range, ...
    Resolution=3, ...
    Transparency=0.6)
coverage(rogers_tx3,rtpm, ...
    SignalStrengths=-120:-5, ...
    MaxRange=max_range, ...
    Resolution=3, ...
    Transparency=0.6)

rx1 = rxsite(Name="UE1", ...
    Latitude=45.387805, ...
    Longitude=-75.697409, ...
    AntennaHeight=1);

los(rogers_tx1,rx1)